import esbuild from 'esbuild';
import process from 'process';
import { readFile } from 'node:fs/promises';
import { builtinModules } from 'node:module';
import { sanitizeViewerSource } from './scripts/sanitize-viewer.mjs';

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */`;
const prod = process.argv[2] === 'production';

// The vendored drawio viewer carries createElement("script") call sites that
// trip the plugin-review scanner. The scrub lives in scripts/sanitize-viewer.mjs
// — shared with tests/sanitizeViewer.test.ts so the tested transform is exactly
// the shipped one — keeping the committed viewer.min.txt a pristine copy of
// upstream. It throws (failing the build loudly) whenever the minified shape
// drifts from the pinned snippets.
const sanitizeDrawioViewerPlugin = {
  name: 'sanitize-drawio-viewer',
  setup(build) {
    build.onLoad({ filter: /viewer\.min\.txt$/ }, async (args) => {
      const original = await readFile(args.path, 'utf8');
      return { contents: sanitizeViewerSource(original), loader: 'text' };
    });
  },
};

// esbuild preserves dynamic import() of *external* modules as a native import()
// whenever the target supports the syntax (es2020+), even in cjs output. Obsidian
// loads plugins through its own CJS loader in the Electron renderer, where a native
// import("node:path") is resolved as a URL fetch and rejects with "Failed to fetch
// dynamically imported module" — which broke every desktop editor mount in 0.4.0.
// `supported: { 'dynamic-import': false }` (below) forces the require() lowering;
// this guard fails the build loudly if a native import of a Node built-in or
// electron ever reappears in the bundle.
const guardNativeNodeImportsPlugin = {
  name: 'guard-native-node-imports',
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0) return;
      const out = await readFile('main.js', 'utf8');
      for (const [, spec] of out.matchAll(/import\(\s*["']([^"']+)["']\s*\)/g)) {
        const bare = spec.replace(/^node:/, '');
        if (spec.startsWith('node:') || spec === 'electron' || builtinModules.includes(bare)) {
          throw new Error(
            `guard-native-node-imports: main.js contains a native dynamic import("${spec}"). ` +
            `Obsidian's renderer cannot resolve it at runtime. Ensure 'dynamic-import' stays ` +
            `disabled in the esbuild 'supported' option so it lowers to require().`,
          );
        }
      }
    });
  },
};

const context = await esbuild.context({
  plugins: [sanitizeDrawioViewerPlugin, guardNativeNodeImportsPlugin],
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian', 'electron',
    '@codemirror/autocomplete', '@codemirror/collab', '@codemirror/commands',
    '@codemirror/language', '@codemirror/lint', '@codemirror/search',
    '@codemirror/state', '@codemirror/view',
    '@lezer/common', '@lezer/highlight', '@lezer/lr',
    ...builtinModules,
    'node:*',
  ],
  format: 'cjs',
  target: 'es2021',
  // See guardNativeNodeImportsPlugin: without this, dynamic import('node:*')
  // stays a native import() (es2021 supports the syntax) and rejects at runtime
  // inside Obsidian's CJS plugin loader. Disabling it lowers every dynamic
  // import to a promise-wrapped require(), which is lazy (evaluated at the call
  // site, not at module load), so the mobile-safety rule in CLAUDE.md still holds.
  supported: { 'dynamic-import': false },
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  loader: { '.txt': 'text' },
  outfile: 'main.js',
  minify: prod,
});

if (prod) { await context.rebuild(); await context.dispose(); process.exit(0); }
else { await context.watch(); }
